global:
  scrape_interval: 15s

scrape_configs:
  - job_name: "prometheus"
    static_configs:
      - targets: ["prometheus:9090"]

  - job_name: "auth-service"
    static_configs:
      - targets: ["auth-service:8081"]

  - job_name: "post-service"
    static_configs:
      - targets: ["post-service:8087"]

  - job_name: "message-service"
    static_configs:
      - targets: ["message-service:8093"]

  - job_name: "notification-service"
    static_configs:
      - targets: ["notification-service:8084"]

  - job_name: "upload-service"
    static_configs:
      - targets: ["upload-service:8089"]

  - job_name: "recomment-service"
    static_configs:
      - targets: ["recomment-service:8086"]
